package com.clt.shp.dress.sql;

public interface DressSql{
	String DRESS_INSERT = 
	  "INSERT INTO SALE_BOARD_RVW"
	  + "( SALE_BOARD_RPY_SEQ"
      + ", SALE_BOARD_SEQ"
      + ", GOODS_CD"
      + ", ENTR_NO"
      + ", BUL_TIT_NM"
      + ", BUL_CONT"
      + ", RPY_LVL"
      + ", PAR_SALE_BOARD_RPY_SN"
      + ", QRY_CNT"
      + ", LKE_CNT"
      + ", RGST_ID"
      + ", RGST_DATE"
      + ", UPDT_ID"
      + ", UPDT_DATE"
      + ", USE_YN"
      + ", IMG_PATH"
      + ", IMG_NM"
	  + ") VALUES"
	  + "( SQ_SALE_BOARD_RPY_SEQ.NEXTVAL"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", SYSDATE"
	  + ", ?"
	  + ", SYSDATE"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ")"
	;
	
	String DRESS_SELECT =
	  "SELECT SALE_BOARD_RPY_SEQ"
	  + ", SALE_BOARD_SEQ"
      + ", GOODS_CD"
      + ", ENTR_NO"
      + ", BUL_TIT_NM"
      + ", BUL_CONT"
      + ", RPY_LVL"
      + ", PAR_SALE_BOARD_RPY_SN"
      + ", QRY_CNT"
      + ", LKE_CNT"
      + ", RGST_ID"
      + ", RGST_DATE"
      + ", UPDT_ID"
      + ", UPDT_DATE"
      + ", USE_YN"
      + ", IMG_PATH"
      + ", IMG_NM"
	  + "  FROM SALE_BOARD_RVW"
	  + " WHERE 1 = 1"
	  + " AND SALE_BOARD_RPY_SEQ = ?"
	;
	
	String DRESS_LIST =
      "SELECT SALE_BOARD_RPY_SEQ"
    + ", SALE_BOARD_SEQ"
    + ", GOODS_CD"
    + ", ENTR_NO"
    + ", BUL_TIT_NM"
    + ", BUL_CONT"
    + ", RPY_LVL"
    + ", PAR_SALE_BOARD_RPY_SN"
    + ", QRY_CNT"
    + ", LKE_CNT"
    + ", RGST_ID"
    + ", RGST_DATE"
    + ", UPDT_ID"
    + ", UPDT_DATE"
    + ", USE_YN"
    + ", IMG_PATH"
    + ", IMG_NM"
	+ "  FROM SALE_BOARD_RVW"
	+ " WHERE 1 = 1"
	+ " ORDER BY SALE_BOARD_RPY_SEQ ASC"
	;
	
	String DRESS_UPDATE =
	  "UPDATE SALE_BOARD_RVW "
	+ "   SET BUL_TIT_NM = ?"
	+ "     , BUL_CONT = ?"
	+ "     , USE_YN = ?"
	+ "		, IMG_PATH = ?"
	+ "		, IMG_NM = ?"
	+ " WHERE 1=1"
	+ " AND SALE_BOARD_RPY_SEQ = ?"
	;
	
	String DRESS_DELETE = 
	  "DELETE FROM SALE_BOARD_RVW "
	+ " WHERE 1=1 "
	+ " AND SALE_BOARD_RPY_SEQ = ?"
	;
	
}