package com.clt.shp.dress.sql;

public interface DressSql{
	String DRESS_INSERT = 
	  "INSERT INTO SALE_BOARD_RVW"
	  + "( SALE_BOARD_RPY_SEQ"
      + ", SALE_BOARD_SEQ"
      + ", GOODS_CD"
      + ", ENTR_NO"
      + ", BUL_TIT_NM"
      + ", BUL_CONT"
      + ", RPY_LVL"
      + ", PAR_SALE_BOARD_RPY_SN"
      + ", QRY_CNT"
      + ", LKE_CNT"
      + ", RGST_ID"
      + ", RGST_DATE"
      + ", UPDT_ID"
      + ", UPDT_DATE"
      + ", USE_YN"
      + ", IMG_PATH"
      + ", IMG_NM"
	  + ", ORD_NO"
	  + ", RVW_TAG"
	  + ") VALUES"
	  + "( SQ_SALE_BOARD_RPY_SEQ.NEXTVAL"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", SYSDATE"
	  + ", ?"
	  + ", SYSDATE"
	  + ", 'Y'"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ", ?"
	  + ")"
	;
	
	String DRESS_SELECT =
	  "SELECT SALE_BOARD_RPY_SEQ"
	  + ", SALE_BOARD_SEQ"
      + ", GOODS_CD"
      + ", ENTR_NO"
      + ", BUL_TIT_NM"
      + ", BUL_CONT"
      + ", RPY_LVL"
      + ", PAR_SALE_BOARD_RPY_SN"
      + ", QRY_CNT"
      + ", LKE_CNT"
      + ", RGST_ID"
      + ", RGST_DATE"
      + ", UPDT_ID"
      + ", UPDT_DATE"
      + ", USE_YN"
      + ", IMG_PATH"
      + ", IMG_NM"
	  + ", IMG_NM"
	  + ", RVW_TAG"
	  + "  FROM SALE_BOARD_RVW"
	  + " WHERE 1 = 1"
	  + " AND SALE_BOARD_RPY_SEQ = ?"
	;
	
	String DRESS_LIST =
      "SELECT SALE_BOARD_RPY_SEQ"
    + ", SALE_BOARD_SEQ"
    + ", GOODS_CD"
    + ", ENTR_NO"
    + ", BUL_TIT_NM"
    + ", BUL_CONT"
    + ", RPY_LVL"
    + ", PAR_SALE_BOARD_RPY_SN"
    + ", QRY_CNT"
    + ", LKE_CNT"
    + ", RGST_ID"
    + ", RGST_DATE"
    + ", UPDT_ID"
    + ", UPDT_DATE"
    + ", USE_YN"
    + ", IMG_PATH"
    + ", IMG_NM"
    + ", RVW_TAG"
	+ "  FROM SALE_BOARD_RVW"
	+ " WHERE 1 = 1"
	+ " ORDER BY SALE_BOARD_RPY_SEQ ASC"
	;
	
	String DRESS_UPDATE =
	  "UPDATE SALE_BOARD_RVW "
	+ "   SET BUL_TIT_NM = ?"
	+ "     , BUL_CONT = ?"
	+ "     , USE_YN = ?"
	+ "		, IMG_PATH = ?"
	+ "		, IMG_NM = ?"
    + "		, RVW_TAG = ?"
	+ " WHERE 1=1"
	+ " AND SALE_BOARD_RPY_SEQ = ?"
	;
	
	String DRESS_DELETE = 
	  "DELETE FROM SALE_BOARD_RVW "
	+ " WHERE 1=1 "
	+ " AND SALE_BOARD_RPY_SEQ = ?"
	;
	
	String GOODS_DTL_DRESS_LIST =
      "SELECT SALE_BOARD_RPY_SEQ"
    + ", SALE_BOARD_SEQ"
    + ", GOODS_CD"
    + ", ENTR_NO"
    + ", BUL_TIT_NM"
    + ", BUL_CONT"
    + ", RPY_LVL"
    + ", PAR_SALE_BOARD_RPY_SN"
    + ", QRY_CNT"
    + ", LKE_CNT"
    + ", RGST_ID"
    + ", RGST_DATE"
    + ", UPDT_ID"
    + ", UPDT_DATE"
    + ", USE_YN"
    + ", IMG_PATH"
    + ", IMG_NM"
    + ", RVW_TAG"
	+ "  FROM SALE_BOARD_RVW"
	+ "  WHERE 1 = 1"
	+ "  AND GOODS_CD = ?"	
	+ "  ORDER BY SALE_BOARD_RPY_SEQ ASC"
	;

	String SELECT_WRITE_SALE_RVW =
	 "SELECT ORD.ORD_NO"
	+"	 , ORD.USR_ID"
	+"	 , ORD.ENTR_NO"
	+"	 , ORD.ORD_STAT"
	+"	 , ORD.ORDR_ID"
	+"	 , ORD.ORDR_NM"
	+"	 , ORD.ORDR_PHON"
	+"	 , ORD.ORDR_EMAIL"
	+"	 , ORD.ACQR_PHON"
	+"	 , ORD.ACQR_NM"
	+"	 , ORD.ACQR_ADDR"
	+"	 , ORD.ACQR_ADDR_DTL"
	+"	 , ORD.ACQR_EMAIL"
	+"	 , ORD.PRCL_WAY"
	+"	 , ORD.PACK_WAY"
	+"	 , ORD.PAY_MNY"
	+"	 , ORD.REQ_MEMO"
	+"	 , ORD.ORD_DATE"
	+"	 , ORD.UPDT_DATE"
	+"	 , ORD.UPDT_ID"
	+"	 , ORD.RGST_DATE"
	+"	 , ORD.RGST_ID"
	+"	 , ORD.BILL_NUM"
	+"	 , SBRW.SALE_BOARD_RPY_SEQ"
	+"	 , ORD.SALE_BOARD_SEQ"
	+"	 , ORD.GOODS_CD"
	+"	 , SBRW.RPY_LVL"
	+"	 , SBRW.PAR_SALE_BOARD_RPY_SN"
	+"	 , SBRW.QRY_CNT"
	+"	 , SBRW.LKE_CNT"
	+"	 , SBRW.USE_YN"
	+"	 , GOODS.IMG_PATH"
	+"	 , GOODS.IMG_NM"
	+"   , SALE.BUL_TIT_NM"
	+"   , SALE.BUL_CONT"
	+"  FROM ORD_BASE ORD"
	+"  LEFT OUTER JOIN SALE_BOARD_RVW SBRW ON ORD.ORD_NO = SBRW.ORD_NO"
	+"  LEFT OUTER JOIN GOODS_INFO GOODS ON ORD.GOODS_CD = GOODS.GOODS_CD"
	+"  LEFT OUTER JOIN SALE_BOARD SALE ON ORD.SALE_BOARD_SEQ = SALE.SALE_BOARD_SEQ"
	+" WHERE 1=1"
	+"   AND SBRW.ORD_NO IS NULL"
	+"   AND ORD.USR_ID = ?"
	;
}