CREATE TABLE "HANGANG"."COUPON" 
   (   "COU_NUM" NUMBER, 
   "COU_NAME" VARCHAR2(200 BYTE), 
   "COU_DISCOUNT" NUMBER, 
   "COU_TIME" VARCHAR2(200 BYTE), 
   "COU_COUNT" NUMBER, 
    PRIMARY KEY ("COU_NUM")
     );