INSERT INTO USR_BASE (USR_BASE_SEQ,USR_ID,USR_NM,PASS_WD,USR_BIRTH,EMAIL_ADDR,CELL_NO,LAND_ADDR_BASE,LAND_ADDR_DTL,LAND_POST_NO,LOAD_ADDR_BASE,LOAD_ADDR_DTL,LOAD_POST_NO,PASS_WD_CHG_DATE,LOCK_YN,RGST_ID,RGST_DATE,UPDT_ID,UPDT_DATE,USE_YN) VALUES (SQ_USR_BASE_SEQ.NEXTVAL,'chunkind','김땡땡','1234','1988420','chunkind@naver.com','01012341234',null,null,null,null,null,null,null,'N',null,to_date('22/05/08','RR/MM/DD'),null,null,'Y');


COMMIT: