/******************************************* 유저 **********************************************/
/*유저 삭제*/
DROP USER HANGANG;

/*유저생성*/
CREATE USER HANGANG IDENTIFIED BY VICTORY123;

/*권한 주기*/
GRANT CONNECT, RESOURCE TO HANGANG;

/*** HANGANG 으로 접속 후 생성 ***/
/* 테이블 생성 */
CREATE TABLE MAIN_BOARD(
    MAIN_BOARD_SN NUMBER,
    IMG_PATH VARCHAR2(20 BYTE)
);


/******************************************* 테이블 **********************************************/
DROP SEQUENCE SQ_MEMBER_SEQ;
DROP SEQUENCE SQ_GOODS_INFO_SEQ;
DROP SEQUENCE SQ_QNA_BOARD_SEQ;
DROP SEQUENCE SQ_STD_CD_BASE_SEQ;
DROP SEQUENCE SQ_ENTR_BASE_SEQ;
DROP SEQUENCE SQ_GOODS_CATA_SEQ;
DROP SEQUENCE SQ_SALE_BOARD_RPY_SEQ;
DROP SEQUENCE SQ_ORD_DTL_NO;
DROP SEQUENCE SQ_ORD_BASKET_SEQ;
DROP SEQUENCE SQ_ORD_BASKET_HIST_SEQ;
DROP SEQUENCE SQ_EVENT_INFO_SEQ;
DROP SEQUENCE SQ_COU_INFO_SEQ;
DROP SEQUENCE SQ_DRESSROOM_INFO_SEQ;
DROP SEQUENCE SQ_SALE_BOARD_RVW_SEQ;

DROP TABLE MEMBER;
DROP TABLE USR_BASE;
DROP TABLE BUY;
DROP TABLE PRODUCT_IO;
DROP TABLE EVENT_TBL;
DROP TABLE ONEQNA_TBL;
DROP TABLE STATS_TBL;
DROP TABLE GOODS_INFO;
DROP TABLE GOODS_REVIEW;
DROP TABLE GOODS_QNA;
DROP TABLE DRESSROOM;
DROP TABLE DRESSROOM_TAG;
DROP TABLE DRESSROOM_COMMENT;
DROP TABLE QNA_BOARD;
DROP TABLE STD_CD_BASE;
DROP TABLE ENTR_BASE;
DROP TABLE GOODS_CATA;
DROP TABLE SALE_BOARD_RVW;
DROP TABLE ORD_BASE;
DROP TABLE ORD_DTL;
DROP TABLE COUPON_TBL;
DROP TABLE EVENT_TBL;

--CREATE SEQUENCE SQ_MEMBER_SEQ;
CREATE SEQUENCE SQ_USR_BASE_SEQ;
CREATE SEQUENCE SQ_GOODS_INFO_SEQ;
CREATE SEQUENCE SQ_QNA_BOARD_SEQ;
CREATE SEQUENCE SQ_STD_CD_BASE_SEQ;
CREATE SEQUENCE SQ_ENTR_BASE_SEQ;
CREATE SEQUENCE SQ_GOODS_CATA_SEQ;
CREATE SEQUENCE SQ_SALE_BOARD_SEQ;
CREATE SEQUENCE SQ_SALE_BOARD_RPY_SEQ;
CREATE SEQUENCE SQ_ORD_DTL_NO;
CREATE SEQUENCE SQ_ORD_BASKET_SEQ;
CREATE SEQUENCE SQ_ORD_BASKET_HIST_SEQ;
CREATE SEQUENCE SQ_COU_INFO_SEQ;
CREATE SEQUENCE SQ_EVENT_INFO_SEQ;
CREATE SEQUENCE SQ_DRESSROOM_INFO_SEQ;
CREATE SEQUENCE SQ_SALE_BOARD_RVW_SEQ;

--CREATE TABLE MEMBER
--( MEMBER_SEQ	NUMBER	NOT NULL
--, MEMBER_ID	VARCHAR(100)	NULL
--, MEMBER_NAME	VARCHAR(50)	NULL
--, MEMBER_PWD	VARCHAR(100)	NULL
--, MEMBER_TEL	VARCHAR(100)	NULL
--, BIRTH	VARCHAR(100)	NULL
--, GENDER	CHAR(1)	NULL
--, EMAIL	VARCHAR(100)	NULL
--, CREATED_AT	TIMESTAMP	NULL
--, GRADE	VARCHAR(10)	NULL
--, DEL_FLAG	CHAR(1)	NULL
--, DEL_DATE	DATE	NULL
--, COUPON	VARCHAR(255)	NULL
--, ACCUMULATED_MONEY	NUMBER	NULL
--);

CREATE TABLE USR_BASE
( USR_BASE_SEQ	NUMBER(20)		NOT NULL
, USR_ID	VARCHAR2(200)		NOT NULL
, USR_NM	VARCHAR2(200)		NULL
, PASS_WD	VARCHAR2(200)		NULL
, USR_BIRTH     VARCHAR2(200)   NULL
, EMAIL_ADDR	VARCHAR2(200)		NULL
, CELL_NO	VARCHAR2(100)		NULL
, LAND_ADDR_BASE	VARCHAR2(1000)		NULL
, LAND_ADDR_DTL	VARCHAR2(1000)		NULL
, LAND_POST_NO	VARCHAR2(10)		NULL
, LOAD_ADDR_BASE	VARCHAR2(1000)		NULL
, LOAD_ADDR_DTL	VARCHAR2(1000)		NULL
, LOAD_POST_NO	VARCHAR2(100)		NULL
, PASS_WD_CHG_DATE	DATE		NULL
, LOCK_YN	VARCHAR2(1)		NULL
, RGST_ID	VARCHAR2(200)		NULL
, RGST_DATE	DATE		NULL
, UPDT_ID	VARCHAR2(200)		NULL
, UPDT_DATE	DATE		NULL
, USE_YN	VARCHAR2(1)		NULL
, USR_GRDE	VARCHAR2(20)	NULL	/*ORD002 / 회원등급*/
, ADM_GRDE	VARCHAR2(20)	NULL	/*ORD003 /  관리자등급*/
);

CREATE TABLE BUY
( ORDER_NUM	NUMBER	NOT NULL
, RES_NAME	VARCHAR(20)	NULL
, RES_TEL	VARCHAR(100)	NULL
, RES_ADDR	VARCHAR(100)	NULL
, BETTER_ADDR	VARCHAR(100)	NULL
, POSTCODE	NUMBER	NULL
, RES_REQUIREMENT	VARCHAR(200)	NULL
, TOTAL_PRICE	NUMBER	NULL
, ORDER_DATE	DATE	NULL
, MEMBER_ID	VARCHAR(100)	NOT NULL
);

CREATE TABLE PRODUCT_IO
( IO_NUM	NUMBER	NOT NULL
, ORDER_NUM2	NUMBER	NOT NULL
, KEY	VARCHAR(255)	NOT NULL
, AMOUNT	NUMBER	NULL
, STATUS	VARCHAR(10)	NULL
, PDATE	DATE	NULL
);

CREATE TABLE EVENT_TBL 
( EVE_NUM	NUMBER	NOT NULL
, EVE_TITLE	VARCHAR2(30)	NULL
, EVE_CON	VARCHAR2(30)	NULL
, EVE_REGD	DATE	NULL
, EVE_DATE	DATE	NULL
);

CREATE TABLE ONEQNA_TBL
( ONEQ_NUM	NUMBER	NOT NULL
, ONEQ_TITLE	VARCHAR2(30)	NULL
, ONEQ_NAME	VARCHAR2(30)	NULL
, ONEQ_DATE	DATE	NULL
, ONEQ_CON	VARCHAR2(30)	NULL
);

CREATE TABLE STATS_TBL 
( STATS_CODE	NUMBER	NOT NULL
, WEEK_STATS	NUMBER	NULL
, MONTHLY_STATS	NUMBER	NULL
, DAILY_COUNT	NUMBER	NULL
, WEEK_COUNT	NUMBER	NULL
, MONTHLY_COUNT	NUMBER	NULL
, DEP_COUNT	NUMBER	NULL
, DEP_MONEY	NUMBER	NULL
, DEPCOM_COUNT	NUMBER	NULL
, DEPCOM_MONEY	NUMBER	NULL
, DELI_COUNT	NUMBER	NULL
, DELI_MONEY	NUMBER	NULL
, DELICOM_COUNT	NUMBER	NULL
, DELICOM_MONEY	NUMBER	NULL
, ORDERCOM_COUNT	NUMBER	NULL
, ORDERCOM_MONEY	NUMBER	NULL
, CAN_COUNT	NUMBER	NULL
, CANCOM_COUNT	NUMBER	NULL
, SWAP_COUNT	NUMBER	NULL
, SWAPCOM_COUNT	NUMBER	NULL
, RETURN_COUNT	NUMBER	NULL
, RETURNCOM_COUNT	NUMBER	NULL
);

CREATE TABLE GOODS_INFO
( GOODS_INFO_SEQ NUMBER(20) PRIMARY KEY
, GOODS_CD	NUMBER(12)	NOT NULL /*상품 코드*/
, ENTR_NO	NUMBER(12)	NULL /*거래처 번호*/
, GOODS_NM	VARCHAR2(200)	NULL /*상품이름*/
, GOODS_PRC	NUMBER(12)	NULL /*상품가격*/
, CATGRY_CD	VARCHAR2(20)	NULL /*대분류*/
, CATGRY_CD2	VARCHAR2(20)	NULL /*소분류*/
, INY_QTY	NUMBER(14)	NULL /*재고수량*/
, DLV_PRC	NUMBER(20)	NULL /*배송비*/
, GOODS_SIZE	VARCHAR2(200)	NULL /*상품싸이즈*/
, GOODS_CLR	VARCHAR2(200)	NULL /*상품컬러*/
, IMG_PATH	VARCHAR2(500)	NULL /*이미지경로*/
, IMG_NM	VARCHAR2(300)	NULL /*이미지이름*/
, GOODS_INTR	VARCHAR2(4000)	NULL /*상품소개*/
, SALE_STAT_CD	VARCHAR2(10)	NULL /*판매상태*/
, USE_YN	VARCHAR2(1)	NULL /*사용여부*/
, RGST_ID	VARCHAR2(20)	NULL /*등록자*/
, RGST_DATE	DATE	NULL /*등록일*/
, UPDT_ID	VARCHAR2(20)	NULL /*수정자*/
, UPDT_DATE	DATE	NULL /*수정일*/
);

ALTER TABLE GOODS_INFO ADD CATGRY_CD	VARCHAR2(20) NOT NULL; /*카테고리 1댑스*/
ALTER TABLE GOODS_INFO ADD CATGRY_CD2	VARCHAR2(20) NOT NULL; /*카테고리 2댑스*/

-- 테이블 삭제
--CREATE TABLE GOODS_REVIEW
--( REVIEW_ID	NUMBER	NOT NULL
--, REVIEW_TYPE	NUMBER	NOT NULL
--, GOODS_CATEGORY_ID	NUMBER	NOT NULL
--, SIZE_ID	NUMBER	NOT NULL
--, COLOR_ID2	NUMBER	NOT NULL
--, KEY	VARCHAR(255)	NOT NULL
--, USER_ID	NUMBER	NULL
--, USER_HEIGHT	NUMBER	NULL
--, REVIEW_DESCRIPTION	VARCHAR2(3000)	NULL
--, REVIEW_DATE	DATE	NULL
--, REVIEW_IMAGE	VARCHAR2(3000)	NULL
--);

CREATE TABLE "SALE_BOARD_RVW" (
  "SALE_BOARD_RPY_SEQ"	NUMBER(20)		NOT NULL,
  "SALE_BOARD_SEQ"	NUMBER(12)		NOT NULL,
  "GOODS_CD"	NUMBER(12)		NOT NULL,
  "ENTR_NO"	NUMBER(12)		NOT NULL,
  "BUL_TIT_NM"	VARCHAR2(100)		NULL,
  "BUL_CONT"	VARCHAR2(500)		NULL,
  "RPY_LVL"	NUMBER(3)		NULL,
  "PAR_SALE_BOARD_RPY_SN"	NUMBER(12)		NULL,
  "QRY_CNT"	NUMBER(14)		NULL,
  "LKE_CNT"	NUMBER(14)		NULL,
  "RGST_ID"	VARCHAR2(200)		NULL,
  "RGST_DATE"	DATE		NULL,
  "UPDT_ID"	VARCHAR2(200)		NULL,
  "UPDT_DATE"	DATE		NULL,
  "USE_YN"	VARCHAR2(1)		NULL,
  "IMG_PATH"	VARCHAR2(500)		NULL,
  "IMG_NM"	VARCHAR2(300)		NULL,
  "ORD_NO"	VARCHAR2(200)		NULL,
  "RVW_TAG"	VARCHAR2(200)		NULL
);

CREATE TABLE GOODS_QNA 
( GOODS_QNA_ID	NUMBER	NOT NULL
, GOODS_CATEGORY_ID	NUMBER	NOT NULL
, SIZE_ID	NUMBER	NOT NULL
, COLOR_ID2	NUMBER	NOT NULL
, KEY	VARCHAR(255)	NOT NULL
, USER_ID	NUMBER	NULL
, GOODS_QNA_ANSWER	NUMBER	NULL
, GOODS_QNA_DESCRIPTION	VARCHAR2(1000)	NULL
, GOODS_QNA_DATE	DATE	NULL
, GOODS_QNA_SECRET	NUMBER	NULL
, GOODS_QNA_PWD	NUMBER	NULL
);

CREATE TABLE DRESSROOM
( DRESSROOM_ID	NUMBER	NOT NULL
, TAG_ID	NUMBER	NOT NULL
, USER_ID	NUMBER	NULL
, DRESSROOM_NAME	VARCHAR2(40)	NULL
, DRESSROOM_DESCRIPTION	VARCHAR2(3000)	NULL
, DRESSROOM_DATE	DATE	NULL
, DRESSROOM_LIKE	NUMBER	NULL
);

CREATE TABLE DRESSROOM_TAG
( TAG_ID	NUMBER	NOT NULL
, TAG_NAME	VARCHAR2(20)	NULL
);

CREATE TABLE DRESSROOM_COMMENT
( DRESSROOM_COMMENT_ID	NUMBER	NOT NULL
, DRESSROOM_ID	NUMBER	NOT NULL
, USER_ID	NUMBER	NULL
, DRESSROOM_COMMENT_DATE	DATE	NULL
, DRESSROOM_COMMENT_DESCRIPTION	VARCHAR2(3000)	NULL
);

CREATE TABLE QNA_BOARD (
	QNA_BOARD_SEQ	NUMBER(20)	NOT NULL,
	TIT_NM	VARCHAR2(1000)	NULL,
	CONT	CLOB	NULL,
	RGST_ID	VARCHAR2(200)	NULL,
	RGST_DATE	DATE	NULL,
	UPDT_ID	VARCHAR2(200)	NULL,
	UPDT_DATE	DATE	NULL,
	QNA_TP	VARCHAR(20)	NULL,
	ANSR_STAT	VARCHAR2(20)	NULL,
	USE_YN	VARCHAR2(1)	NULL,
	PASS_YN	VARCHAR2(1)	NULL,
	PASS_WD	VARCHAR(200)	NULL,
	GOODS_CD	NUMBER(12)	NULL,
	ANSWER	CLOB	NULL
);

CREATE TABLE STD_CD_BASE
( STD_CD_BASE_SEQ	NUMBER	NOT NULL
, CODE_NM	VARCHAR2(200)	NOT NULL
, CODE_VAL	VARCHAR2(200)	NOT NULL
, CODE_DESC	VARCHAR2(2000)	NULL
, GRP_CD	VARCHAR2(200)	NULL
, GRP_ORDR	NUMBER(8)	NULL
, USE_YN	VARCHAR2(1)	NULL
, RGST_ID	VARCHAR2(200)	NULL
, RGST_DATE	DATE	NULL
, UPDT_ID	VARCHAR2(200)	NULL
, UPDT_DATE	DATE	NULL
);

CREATE TABLE ENTR_BASE
( ENTR_NO	NUMBER(12)		NOT NULL
, USR_ID	VARCHAR2(20)		NOT NULL
, ENTR_NM	VARCHAR2(100)		NULL
, BMAN_REG_NO	VARCHAR2(20)		NULL
, PRES_NM	VARCHAR2(100)		NULL
, PRES_TELL	VARCHAR2(20)		NULL
, PRES_EMAIL	VARCHAR2(200)		NULL
, AEMP_NM	VARCHAR2(100)		NULL
, AEMP_TELL	VARCHAR2(20)		NULL
, AEMP_EMAIL	VARCHAR2(200)		NULL
, SCORE	NUMBER(5)		NULL
, LAND_ADDR_BASE	VARCHAR2(1000)		NULL
, LAND_ADDR_DTL	VARCHAR2(1000)		NULL
, LAND_POST_NO	VARCHAR2(10)		NULL
, LOAD_ADDR_BASE	VARCHAR2(1000)		NULL
, LOAD_POST_NO	VARCHAR2(100)		NULL
, OPN_DATE	DATE		NULL
, CLOSE_DATE	DATE		NULL
, OPN_YN	VARCHAR2(1)		NULL
, USE_YN	VARCHAR2(1)		NULL
, RGST_ID	VARCHAR2(20)		NULL
, RGST_DATE	DATE		NULL
, UPDT_ID	VARCHAR2(20)		NULL
, UPDT_DATE	DATE		NULL
);


CREATE TABLE GOODS_CATA
( GOODS_CATA_SEQ	NUMBER(20)		NOT NULL
, CATGRY_CD	VARCHAR2(20)		NOT NULL
, GOODS_CD	NUMBER(12)		NOT NULL
, CATGRY_NM	VARCHAR2(400)		NULL
, NOTE_CONT	VARCHAR2(4000)		NULL
, CLASS_LVL_CD	VARCHAR2(20)		NULL
, UPR_CLASS_CD	VARCHAR2(20)		NULL
, RGST_ID	VARCHAR2(200)		NULL
, RGST_DATE	DATE		NULL
, UPDT_ID	VARCHAR2(200)		NULL
, UPDT_DATE	DATE		NULL
, USE_YN	VARCHAR2(1)		NULL
);

CREATE TABLE SALE_BOARD (
    SALE_BOARD_SEQ	NUMBER(20)		NOT NULL,
    ENTR_NO	NUMBER(12)		NOT NULL,
    GOODS_CD	NUMBER(12)		NOT NULL,
    SALE_STAT_CD	VARCHAR2(2)		NULL,
    BUL_TIT_NM	VARCHAR2(100)		NULL,
    BUL_STRT_DT	DATE		NULL,
    BUL_END_DT	DATE		NULL,
    BUL_YN	VARCHAR2(2)		NULL,
    NTC_SCT_CD	VARCHAR2(2)		NULL,
    BUL_CONT	CLOB		NULL,
    QRY_CNT	NUMBER(14)		NULL,
    LKE_CNT	NUMBER(14)		NULL,
    GOODS_PRC	NUMBER(12)		NULL,
    GOODS_SALE_PRC	NUMBER(12)		NULL,
    PRCL_WAY	VARCHAR2(100)		NULL,
    SALE_CNT	NUMBER(12)		NULL,
    RGST_ID	VARCHAR2(200)		NULL,
    RGST_DATE	DATE		NULL,
    UPDT_ID	VARCHAR2(200)		NULL,
    UPDT_DATE	DATE		NULL,
    USE_YN	VARCHAR2(1)		NULL,
    DESCRIPTION	VARCHAR2(100)		NULL
);

CREATE TABLE "ORD_BASE" (
    "ORD_NO"	VARCHAR2(200)		NOT NULL,
    "USR_ID"	VARCHAR2(200)		NOT NULL,
    "ORD_STAT"	VARCHAR2(8)		NULL,
    "ORDR_ID"	VARCHAR2(200)		NULL,
    "ORDR_NM"	VARCHAR2(200)		NULL,
    "ORDR_PHON"	VARCHAR2(20)		NULL,
    "ORDR_EMAIL"	VARCHAR2(200)		NULL,
    "ACQR_PHON"	VARCHAR2(20)		NULL,
    "ACQR_NM"	VARCHAR2(200)		NULL,
    "ACQR_ADDR"	VARCHAR2(1000)		NULL,
    "ACQR_ADDR_DTL"	VARCHAR2(500)		NULL,
    "ACQR_EMAIL"	VARCHAR2(200)		NULL,
    "PRCL_WAY"	VARCHAR2(100)		NULL,
    "PACK_WAY"	VARCHAR2(100)		NULL,
    "PAY_WAY"	VARCHAR2(100)		NULL,
    "PAY_MNY"	NUMBER(12)		NULL,
    "REQ_MEMO"	VARCHAR2(500)		NULL,
    "ORD_DATE"	DATE		NULL,
    "UPDT_DATE"	DATE		NULL,
    "UPDT_ID"	VARCHAR2(200)		NULL,
    "RGST_DATE"	DATE		NULL,
    "RGST_ID"	VARCHAR2(200)		NULL,
    "BILL_NUM"	NUMBER(12)		NULL,
    "SALE_BOARD_SEQ"	NUMBER(20)		NOT NULL,
    "ENTR_NO"	NUMBER(12)		NOT NULL,
    "GOODS_CD"	NUMBER(12)		NOT NULL
);

CREATE TABLE ORD_DTL (
	ORD_DTL_NO	NUMBER(12)	NOT NULL,
	USR_ID	VARCHAR2(20)	NOT NULL,
	ORD_NO	VARCHAR2(200)	NOT NULL,
	GOODS_NM	VARCHAR2(200)	NULL,
	GOODS_CD	NUMBER(12)	NULL,
	GOODS_QTY	NUMBER	NULL,
	UPDT_DATE	DATE	NULL,
	UPDT_ID	VARCHAR2(200)	NULL,
	RGST_DATE	DATE	NULL,
	RGST_ID	VARCHAR2(20)	NULL
);

CREATE TABLE ORD_BASKET (
  ORD_BASKET_SEQ	NUMBER(20)		NOT NULL,
  USR_ID	VARCHAR2(200)		NOT NULL,
  GOODS_QTY	NUMBER(12)		NULL,
  PRCL_WAY	VARCHAR2(100)		NULL,
  PACK_WAY	VARCHAR2(100)		NULL,
  RGST_DATE	DATE		NULL,
  USE_YN	VARCHAR2(1)		NULL,
  SALE_BOARD_SEQ	NUMBER(20)		NOT NULL,
  GOODS_CD	NUMBER(12)		NOT NULL,
  ENTR_NO	NUMBER(12)		NOT NULL
);

CREATE TABLE ORD_BASKET_HIST (
   ORD_BASKET_HIST_SEQ	NUMBER(20)		NOT NULL,
   ORD_BASKET_SEQ	NUMBER(20)		NOT NULL,
   USR_ID	VARCHAR2(200)		NOT NULL,
   GOODS_CD	NUMBER(12)		NULL,
   GOODS_QTY	NUMBER(12)		NULL,
   RGST_ID	VARCHAR2(200)		NULL,
   RGST_DATE	DATE		NULL,
   HIST_MEMO	VARCHAR2(2000)		NULL
);

CREATE TABLE COUPON_TBL (
	COU_INFO_SEQ NUMBER(20) 	PRIMARY KEY, 	/*쿠폰 시퀀스*/
	COU_NUM		 NUMBER(12)		NOT NULL,		/*쿠폰 코드*/
	COU_NAME	 VARCHAR2(200)	NULL,			/*쿠폰 이름*/
	COU_DISCOUNT NUMBER(12)		NULL,			/*쿠폰 할인율*/
	COU_REGIST_DATE	DATE		NULL,			/*쿠폰 등록 날짜*/
	COU_END_DATE	DATE		NULL,			/*쿠폰 만료 날짜*/
	COU_COUNT	 NUMBER(12)		NULL			/*쿠폰 개수*/
);

CREATE TABLE EVENT_TBL (
	EVENT_INFO_SEQ 	NUMBER(20) 	PRIMARY KEY, 	/*이벤트 시퀀스*/
	EVENT_NUM		NUMBER(12)	NOT NULL,		/*이벤트 코드*/
	EVENT_NAME	 	VARCHAR2(200)	NULL,		/*이벤트 이름*/
	IMG_PATH		VARCHAR2(500)	NULL,		/*이미지경로*/
	IMG_NM			VARCHAR2(300)	NULL, 		/*이미지이름*/
	EVENT_REGIST_DATE	DATE		NULL,		/*이벤트 등록 날짜*/
	EVENT_END_DATE		DATE		NULL		/*이벤트 만료 날짜*/
);