package com.clt.shp.main.sql;

public interface MainSql{
	String SELECT_LIST_MAIN_HOME = 
	 "SELECT GOODS.GOODS_CD"
	+"     , GOODS.ENTR_NO"
	+"     , GOODS.GOODS_NM"
	+"     , GOODS.GOODS_PRC"
	+"     , GOODS.INY_QTY"
	+"     , GOODS.DLV_PRC"
	+"     , GOODS.GOODS_SIZE"
	+"     , GOODS.GOODS_CLR"
	+"     , GOODS.IMG_PATH"
	+"     , GOODS.IMG_NM"
	+"     , GOODS.GOODS_INTR"
	+"     , GOODS.SALE_STAT_CD"
	+"     , GOODS.CATGRY_CD"
	+"     , GOODS.CATGRY_CD2"
	+"     , GOODS.USE_YN"
	+"     , GOODS.RGST_ID"
	+"     , GOODS.RGST_DATE"
	+"     , GOODS.UPDT_ID"
	+"     , GOODS.UPDT_DATE"
	+"     , SALE.SALE_BOARD_SEQ"
	+"     , SALE.SALE_STAT_CD"
	+"     , SALE.BUL_TIT_NM"
	+"     , SALE.BUL_STRT_DT"
	+"     , SALE.BUL_END_DT"
	+"     , SALE.BUL_YN"
	+"     , SALE.NTC_SCT_CD"
	+"     , SALE.BUL_CONT"
	+"     , SALE.QRY_CNT"
	+"     , SALE.LKE_CNT"
	+"     , SALE.GOODS_PRC"
	+"     , SALE.GOODS_SALE_PRC"
	+"     , SALE.PRCL_WAY"
	+"     , SALE.SALE_CNT"
	+"     , SALE.RGST_ID"
	+"     , SALE.RGST_DATE"
	+"     , SALE.UPDT_ID"
	+"     , SALE.UPDT_DATE"
	+"     , SALE.USE_YN"
	+"     , SALE.DESCRIPTION"
	+"  FROM SALE_BOARD SALE"
	+"     , GOODS_INFO GOODS"
	+" WHERE 1=1"
	+"   AND SALE.GOODS_CD = GOODS.GOODS_CD"
	+"   AND SALE.ENTR_NO = GOODS.ENTR_NO"
	+"   AND ROWNUM < 11"
	+" ORDER BY SALE.LKE_CNT DESC"
	;
	
	String SELECT_LIST_MAIN_CATE = 
	 "SELECT GOODS.GOODS_CD"
	+"     , GOODS.ENTR_NO"
	+"     , GOODS.GOODS_NM"
	+"     , GOODS.GOODS_PRC"
	+"     , GOODS.INY_QTY"
	+"     , GOODS.DLV_PRC"
	+"     , GOODS.GOODS_SIZE"
	+"     , GOODS.GOODS_CLR"
	+"     , GOODS.IMG_PATH"
	+"     , GOODS.IMG_NM"
	+"     , GOODS.GOODS_INTR"
	+"     , GOODS.SALE_STAT_CD"
    +"     , GOODS.CATGRY_CD"
    +"     , GOODS.CATGRY_CD2"
	+"     , GOODS.USE_YN"
	+"     , GOODS.RGST_ID"
	+"     , GOODS.RGST_DATE"
	+"     , GOODS.UPDT_ID"
	+"     , GOODS.UPDT_DATE"
	+"     , SALE.SALE_BOARD_SEQ"
	+"     , SALE.SALE_STAT_CD"
	+"     , SALE.BUL_TIT_NM"
	+"     , SALE.BUL_STRT_DT"
	+"     , SALE.BUL_END_DT"
	+"     , SALE.BUL_YN"
	+"     , SALE.NTC_SCT_CD"
	+"     , SALE.BUL_CONT"
	+"     , SALE.QRY_CNT"
	+"     , SALE.LKE_CNT"
	+"     , SALE.GOODS_PRC"
	+"     , SALE.GOODS_SALE_PRC"
	+"     , SALE.PRCL_WAY"
	+"     , SALE.SALE_CNT"
	+"     , SALE.RGST_ID"
	+"     , SALE.RGST_DATE"
	+"     , SALE.UPDT_ID"
	+"     , SALE.UPDT_DATE"
	+"     , SALE.USE_YN"
	+"     , SALE.DESCRIPTION"
	+"  FROM SALE_BOARD SALE"
	+"     , GOODS_INFO GOODS"
	+" WHERE 1=1"
	+"   AND SALE.GOODS_CD = GOODS.GOODS_CD"
	+"   AND SALE.ENTR_NO = GOODS.ENTR_NO"
	;
	
}